### ISSUE TITLE
TerminalEmulator

### ISSUE THREAD

**Issue by ShevT** [TeamEOS/vendor_eos#2]
Hi!
Please, fix TerminalEmulator.
After ruunning:
E/AndroidRuntime( 4521): FATAL EXCEPTION: main
E/AndroidRuntime( 4521): Process: jackpal.androidterm, PID: 4521
E/AndroidRuntime( 4521): java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/app/TerminalEmulator/TerminalEmulator.apk"],nativeLibraryDirectories=[/system/app/TerminalEmulator/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjackpal-termexec2.so"
E/AndroidRuntime( 4521):    at java.lang.Runtime.loadLibrary(Runtime.java:366)
E/AndroidRuntime( 4521):    at java.lang.System.loadLibrary(System.java:988)
E/AndroidRuntime( 4521):    at jackpal.androidterm.TermExec.<clinit>(TermExec.java:22)
E/AndroidRuntime( 4521):    at jackpal.androidterm.ShellTermSession.createSubprocess(ShellTermSession.java:153)

lacking library libjackpal-termexec2.so

**Comment by akhilnarang** [comment]
The libs aren't being installed along with the apk

**Comment by ShevT** [comment]
This library must be copied as a https://github.com/TeamEOS/vendor_eos/blob/lp5.1/prebuilt/common/lib/libjackpal-androidterm5.so

**Comment by bigrushdog** [comment]
I promise I know how to copy a prebuilt lib guys. 
https://github.com/TeamEOS/vendor_eos/blob/lp5.1/config/common.mk#L45

I'll update the app and bring in the new needed lib tonight.

**Comment by ShevT** [comment]
ok. For myself, I have long made a patch.

**Comment by ShevT** [comment]
Excellent! https://github.com/TeamEOS/vendor_eos/commit/605ea1cb77bf5199c0d9b8de310b8cc80346f061
